# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\xed\x01\n\x07Updates\x12$\n\x06tracks\x18\x01 \x03(\x0b\x32\x14.Updates.TrackUpdate\x1a\xbb\x01\n\x0bTrackUpdate\x12\x11\n\x04uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05range\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x1d\n\x10position_alt_msl\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x12\n\x05speed\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x14\n\x07\x64\x65leted\x18\x05 \x01(\x08H\x04\x88\x01\x01\x42\x07\n\x05_uuidB\x08\n\x06_rangeB\x13\n\x11_position_alt_mslB\x08\n\x06_speedB\n\n\x08_deletedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATES']._serialized_start=15
  _globals['_UPDATES']._serialized_end=252
  _globals['_UPDATES_TRACKUPDATE']._serialized_start=65
  _globals['_UPDATES_TRACKUPDATE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
