# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track_udp.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftrack_udp.proto\"\xfc\x03\n\x06Tracks\x12\x1d\n\x05track\x18\x01 \x03(\x0b\x32\x0e.Tracks.Update\x1a\xd2\x03\n\x06Update\x12\x11\n\x04uuid\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x12\n\x05speed\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x0f\n\x02\x61z\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x0f\n\x02\x65l\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x12\n\x05range\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x19\n\x0cposition_lat\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x19\n\x0cposition_lon\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x1d\n\x10position_alt_msl\x18\x08 \x01(\x02H\x07\x88\x01\x01\x12 \n\x13radar_cross_section\x18\t \x01(\x02H\x08\x88\x01\x01\x12\x17\n\nprediction\x18\n \x01(\x02H\t\x88\x01\x01\x12\x17\n\nconfidence\x18\x0b \x01(\x02H\n\x88\x01\x01\x12\x19\n\x0csource_class\x18\x0c \x01(\x02H\x0b\x88\x01\x01\x42\x07\n\x05_uuidB\x08\n\x06_speedB\x05\n\x03_azB\x05\n\x03_elB\x08\n\x06_rangeB\x0f\n\r_position_latB\x0f\n\r_position_lonB\x13\n\x11_position_alt_mslB\x16\n\x14_radar_cross_sectionB\r\n\x0b_predictionB\r\n\x0b_confidenceB\x0f\n\r_source_classb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'track_udp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACKS']._serialized_start=20
  _globals['_TRACKS']._serialized_end=528
  _globals['_TRACKS_UPDATE']._serialized_start=62
  _globals['_TRACKS_UPDATE']._serialized_end=528
# @@protoc_insertion_point(module_scope)
